# Generated by Django 6.0.3 on 2026-03-31 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
